/** Data-only transport. No tools, credentials, backend or permission callbacks. */
export interface LLMTransport {
  send(serializedRequest: string, signal: AbortSignal): Promise<string>;
}
/** Offline test double; responses are supplied explicitly, never generated by a network call. */
export class MockLLMTransport implements LLMTransport {
  readonly requests: string[] = [];
  constructor(private readonly responses: readonly string[]) {}
  async send(request: string, signal: AbortSignal): Promise<string> {
    if (signal.aborted) { throw new Error('Transport cancelled'); }
    const index = this.requests.push(request) - 1;
    if (index >= this.responses.length) { throw new Error('No mock response available'); }
    return this.responses[index];
  }
}
